# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-20 14:08
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', DjangoUeditor.models.UEditorField(max_length=200000, verbose_name='content')),
                ('date', models.DateField(auto_now_add=True, verbose_name='create_date')),
            ],
            options={
                'verbose_name': 'article',
                'verbose_name_plural': 'article',
            },
        ),
    ]
