# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-23 13:50
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180420_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('cover', models.ImageField(upload_to=b'', verbose_name='product_image')),
                ('code', models.CharField(max_length=100, verbose_name='product code')),
                ('power', models.CharField(max_length=100, verbose_name='power')),
                ('electric_data', models.CharField(max_length=100, verbose_name='electric data')),
                ('beam_angle', models.CharField(max_length=100, verbose_name='beam angle')),
                ('color_temperature', models.CharField(max_length=100, verbose_name='color temperature')),
                ('ip_class', models.CharField(max_length=100, verbose_name='ip class')),
                ('fixture_size', models.CharField(max_length=100, verbose_name='fixture size')),
                ('cutout_size', models.CharField(max_length=100, verbose_name='cutout size')),
                ('led_source', models.CharField(max_length=100, verbose_name='led source')),
                ('fixture_material', models.CharField(max_length=100, verbose_name='fixture material')),
                ('finish', models.CharField(max_length=100, verbose_name='finish')),
                ('more_info', DjangoUeditor.models.UEditorField(max_length=200000, verbose_name='more info')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='type name')),
            ],
            options={
                'verbose_name': 'All product type',
                'verbose_name_plural': 'All product type',
            },
        ),
        migrations.CreateModel(
            name='Site_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='image name')),
                ('link', models.URLField(verbose_name='link')),
                ('image', models.ImageField(upload_to=b'', verbose_name='image')),
            ],
            options={
                'verbose_name': 'site image',
                'verbose_name_plural': 'site image',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='slide name')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Site_image')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slide',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Product_type'),
        ),
    ]
