# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-28 14:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_article_descript'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 4, 28, 14, 5, 5, 425588, tzinfo=utc), verbose_name='create_time'),
            preserve_default=False,
        ),
    ]
