# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-04-28 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_article_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='create_date',
            field=models.DateField(verbose_name='create_time'),
        ),
    ]
