# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-05-09 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='home gallery name')),
                ('show_type', models.IntegerField(choices=[(1, '11-1-21'), (2, '12-1-11')], default=1, verbose_name='gallery type')),
                ('img1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Img1', to='index.Site_image')),
                ('img2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Img2', to='index.Site_image')),
                ('img3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Img3', to='index.Site_image')),
                ('img4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Img4', to='index.Site_image')),
                ('img5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Img5', to='index.Site_image')),
                ('img6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Img6', to='index.Site_image')),
            ],
            options={
                'verbose_name': 'Home Gallery',
                'verbose_name_plural': 'Home Gallery',
            },
        ),
    ]
